### ISSUE TITLE
source tags with the type property set create an invalid AMP page

### ISSUE THREAD

**Issue by me4502** [tomoyukikashiro/html2amp#104]
I'm using `gatsby-plugin-html2amp`, and am encountering an issue where Gatsby adds a `type="image/webp` to the WebP `<source>` tags.

`type` is not a valid field for `amp-img`, so therefore should be removed.

**Comment by tomoyukikashiro** [comment]
@me4502 Sorry for my late reply 🙇 I fixed this issue at v1.3.1
