### ISSUE TITLE
Amp Story support

### ISSUE THREAD

**Issue by lvisockas** [tomoyukikashiro/html2amp#14]
While using html2amp with Gatsby, I found an issue, that html2amp is not supporting Amp Stories (https://www.ampproject.org/stories/).

Here's a quick update: https://github.com/lvisockas/html2amp/tree/master

**Comment by tomoyukikashiro** [comment]
@lvisockas 

This module works just a `converter` so does not have plan to support amp-tags which comes from original tags sorry... !
