### ISSUE TITLE
Feature Request: Support img with data-src atrribute

### ISSUE THREAD

**Issue by achinchen** [tomoyukikashiro/html2amp#142]
## Chip-Chat

First, thanks for this great solution for amplify!
Is possible to support img with `data-src` attribue?
If PR is welcomed, I'd like to contribute this project 😇

## Expected Behavior

Process of converting img to amp-img will set `src` from  original `src` or `data-src`.

## Actual Behavior

According to [this-line-of-code](https://github.com/tomoyukikashiro/html2amp/blob/d03e36faf7f1fdd5e1c7dd591badc99d33e6aaac/lib/utils.js#L45), it causes unhandled error when the img without `src` even with `data-src` attribute.

## Steps to Reproduce the Problem

```
const html2amp = require('html2amp')
const html = `
<img data-src="https://images.unsplash.com/photo-1523171067267-bb96f975c4bb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=700&q=80" />`
const amp = html2amp(html, {})
console.log(amp)
```

**Comment by tomoyukikashiro** [comment]
HI, @achinchen 

According to HTML spec, `src` attribute of img tag is [required](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#:~:text=The%20src%20attribute%20is%20required) so I would not support this request.

Im sorry for that 🙇
