### ISSUE TITLE
Do not render invalid images (eg: 404) instead of exiting with a probe-image-size failure

### ISSUE THREAD

**Issue by rpong** [tomoyukikashiro/html2amp#156]
Hi,

We are wondering if there are any plans to make html2amp more lenient, and discard invalid images instead of exiting with a probe-image-size failure.

We forked html2amp to do just that, because we are not in full control of the content our users may copy paste into our pages which we need to generate amp pages on.

Our change:
https://github.com/tomoyukikashiro/html2amp/compare/master...innovation-love:master

We'd like to amend the change and submit a PR if there are indeed plans to make html2amp more lenient for use cases like ours.

Thanks

**Comment by tomoyukikashiro** [comment]
@rpong Thank you for your comments 👍 

Actually we do not expect that use case. ( `img` might not exist and you can not control it.)
So you are more than welcome to contribute this repo by PR 👍 

(I would appreciate more if it includes tests 😅 )

**Comment by tomoyukikashiro** [comment]
clonsed by https://github.com/tomoyukikashiro/html2amp/pull/166
