### ISSUE TITLE
Request: Picture tag support

### ISSUE THREAD

**Issue by STUkh** [tomoyukikashiro/html2amp#40]
Hey! It would be great to support transformations for `<picture>` tag, especially when `gatsby-plugin-html2amp` project depends on this core plugin. Also it will be very useful, because `gatsby-image` use <picture> internally, not <img>.

**Comment by tomoyukikashiro** [comment]
Thank you for issue opening 👍
Let me check it!

**Comment by tomoyukikashiro** [comment]
@STUkh I added `<picture>` support version as `v1.0.0`.
Let me know if you have any question 👍
