### ISSUE TITLE
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds

### ISSUE THREAD

**Issue by beliayeu** [tomoyukikashiro/html2amp#70]
**Problem**
* amp generation throws "RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds"

**Steps to reproduce**
* generate amp for html containing image from https://github.com/image-size/image-size/issues/198

**Considerations**
* per my understanding that is a known issue of image-size library (https://github.com/image-size/image-size/issues/94). it would be great to consider switching to an alternative library like probe-image-size, and/or
* do not break amp generation if image size can not be detected. if size can not be detected, then either remove the image from amp  or provide a default size for it

**Comment by tomoyukikashiro** [comment]
Hi, @beliayeu 

Thank you for your issue let me think for this soon ! 👍

**Comment by tomoyukikashiro** [comment]
@beliayeu I fixed this issue 👍 using `probe-image-size` instead of `image-size`. 
plz use [v1.3.0](https://github.com/tomoyukikashiro/html2amp/releases/tag/v1.3.0)
