### ISSUE TITLE
The author stylesheet specified in tag 'style amp-custom' is too long

### ISSUE THREAD

**Issue by beliayeu** [tomoyukikashiro/html2amp#72]
***Problem***
* html containing more than allowed custom styles is converted to invalid amp

***Suggestions***
* to my mind it would be great to reduce custom styles automatically to the allowed length

***References***
* https://amp.dev/documentation/guides-and-tutorials/learn/spec/amphtml/#maximum-size

**Comment by tomoyukikashiro** [comment]
Hi, @beliayeu 

Thank you for your issue let me think for this soon ! 👍

**Comment by tomoyukikashiro** [comment]
@beliayeu  

I released [v1.3.0](https://github.com/tomoyukikashiro/html2amp/releases/tag/v1.3.0) which has `plugin` options for css and html.  You can modify them using plugins.

plz check [README](https://github.com/tomoyukikashiro/html2amp#options) for more plugin details. 👍
