### ISSUE TITLE
Support forms

### ISSUE THREAD

**Issue by beliayeu** [tomoyukikashiro/html2amp#73]
***Problem***
html containing forms is converted to invalid amp

***Suggestions***
* short term, it would be great to strip all forms
* long term, it would be great to convert html form into amp-form

**Comment by tomoyukikashiro** [comment]
Hi, @beliayeu 

Thank you for your issue let me think for this soon ! 👍

**Comment by tomoyukikashiro** [comment]
@beliayeu 

I released [v1.3.0](https://github.com/tomoyukikashiro/html2amp/releases/tag/v1.3.0) which has `plugin` options for css and html.  You can modify them using plugins.

For now plz implement plugin for support forms.
I'll keep considering this issue.

plz check [README](https://github.com/tomoyukikashiro/html2amp#options) for more plugin details. 👍
