### ISSUE TITLE
Loading Attribute Not Allowed in amp-img

### ISSUE THREAD

**Issue by wesleylhandy** [tomoyukikashiro/html2amp#80]
I'm using the `gatsby-plugin-html2amp` plugin that is dependent upon this package. My site started getting AMP errors in a recent update because Gatsby is adding the 'loading' attribute to images. 

This package ensures the required `amp-img` attributes are present but also adds any other attributes to the transformed image via the spread operator. 

```
utils.js // line 62
const _attrs = { src: url, alt, width: size.width, height: size.height, layout: 'responsive', ...attrs }
```
Could the following be added on the next line before mapping the keys to the new attributes object:

```
try {
  delete _attrs['loading'] 
} catch (err) {
  console.error('Loading property is an "own non-configurable property"')
}
```

The try/catch is probably unnecessary. [Delete should only throw an exception in strict mode if the property was set to non-configurable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/delete#Exceptions), which shouldn't apply here.

**Comment by wesleylhandy** [comment]
There is some discussion within the AMP Project for allowing the 'loading' attribute, but for now it's creating AMP issues:

https://github.com/ampproject/amphtml/issues/21497

**Comment by tomoyukikashiro** [comment]
Hi, @wesleylhandy 

Good catch !
I'll check the PR soon 👀

**Comment by tomoyukikashiro** [comment]
@wesleylhandy merged !!!

https://github.com/tomoyukikashiro/html2amp/releases/tag/v1.1.0

**Comment by wesleylhandy** [comment]
@tomoyukikashiro Thank you!
