### ISSUE TITLE
Broken img styles when in AMP

### ISSUE THREAD

**Issue by ArthurBrito** [tomoyukikashiro/html2amp#82]
My images are with the wrong styles when in AMP mode. I understand that some css are imported when using AMP and all the `!important` are removed.

There's any way I can edit the css for my amp? Or should I implement my css in a different way (e.g avoid using width: 80% for images) to make my styles the same when using AMP? 

Thanks for the amazing plugin :)

**Comment by tomoyukikashiro** [comment]
HI, @ArthurBrito 

The easiest way to fix that problem is that `implement my css in a different way`. 👍 
Because this module does not have any way to modify the author's css... 

I got related issue #72 so let me think for this issue too 👍

**Comment by tomoyukikashiro** [comment]
@ArthurBrito 
I released [v1.3.0](https://github.com/tomoyukikashiro/html2amp/releases/tag/v1.3.0) which has `plugin` options for css and html.  You can modify them using plugins.

plz check [README](https://github.com/tomoyukikashiro/html2amp#options) for more plugin details. 👍
